language: clojure
git:
  submodules: false
  depth: 5
before_install: resources/scripts/switch-to-https-submodules.sh
script: lein build
jdk:
  - openjdk8
  - openjdk11
notifications:
  slack:
    rooms: hexagram30:LQkiA60LztFoZGZ0ojjbRA6m#cicd
